#!/bin/bash

# Cross-Browser Testing Helper Script
# This script helps test the Educard application across different browsers

echo "======================================"
echo "Educard Cross-Browser Testing Helper"
echo "======================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Testing Environment Setup${NC}"
echo "Application URL: http://localhost:3000"
echo ""

# Check if application is running
echo "Checking if application is running..."
if curl -s http://localhost:3000 > /dev/null; then
    echo -e "${GREEN}✓ Application is running${NC}"
else
    echo -e "${YELLOW}⚠ Application is not running. Please start it first:${NC}"
    echo "  docker-compose up -d"
    exit 1
fi

echo ""
echo -e "${BLUE}Browser Testing Instructions${NC}"
echo ""

echo "=== Desktop Browser Testing ==="
echo ""
echo "1. Chrome:"
echo "   - Open: chrome http://localhost:3000"
echo "   - DevTools: F12 or Cmd+Option+I (Mac) / Ctrl+Shift+I (Win)"
echo "   - Responsive Mode: Cmd+Shift+M (Mac) / Ctrl+Shift+M (Win)"
echo ""

echo "2. Firefox:"
echo "   - Open: firefox http://localhost:3000"
echo "   - DevTools: F12 or Cmd+Option+I (Mac) / Ctrl+Shift+I (Win)"
echo "   - Responsive Mode: Cmd+Option+M (Mac) / Ctrl+Shift+M (Win)"
echo ""

echo "3. Safari (macOS only):"
echo "   - Open: open -a Safari http://localhost:3000"
echo "   - DevTools: Cmd+Option+I (enable in Preferences first)"
echo "   - Responsive Mode: Develop > Enter Responsive Design Mode"
echo ""

echo "4. Edge:"
echo "   - Open: microsoft-edge http://localhost:3000"
echo "   - DevTools: F12 or Ctrl+Shift+I"
echo "   - Responsive Mode: Ctrl+Shift+M"
echo ""

echo "=== Responsive Breakpoints to Test ==="
echo ""
echo "Test these screen sizes in DevTools:"
echo "  • 320px  - iPhone SE (small mobile)"
echo "  • 375px  - iPhone 13/14 (medium mobile)"
echo "  • 414px  - iPhone 14 Pro Max (large mobile)"
echo "  • 768px  - iPad Mini/Air (tablet)"
echo "  • 1024px - iPad Pro / Small Desktop"
echo "  • 1280px - Desktop"
echo "  • 1920px - Full HD Desktop"
echo ""

echo "=== Test Scenarios ==="
echo ""
echo "Test these user flows on EACH browser:"
echo ""
echo "1. Registration Flow:"
echo "   • Navigate to /auth/register"
echo "   • Fill in: username, email, password, confirm password"
echo "   • Submit form"
echo "   • Verify redirect to home page"
echo "   • Check for success message"
echo ""

echo "2. Login Flow:"
echo "   • Navigate to /auth/login"
echo "   • Enter credentials"
echo "   • Submit form"
echo "   • Verify redirect and session"
echo ""

echo "3. Browse Threads:"
echo "   • Click on categories"
echo "   • View thread list"
echo "   • Check pagination"
echo "   • Verify sorting works"
echo ""

echo "4. Create Thread:"
echo "   • Click 'New Thread'"
echo "   • Fill in title and content"
echo "   • Use markdown formatting"
echo "   • Submit thread"
echo "   • Verify thread created"
echo ""

echo "5. Reply to Thread:"
echo "   • Open a thread"
echo "   • Click reply button"
echo "   • Write reply with markdown"
echo "   • Submit reply"
echo "   • Verify post appears"
echo ""

echo "6. Edit Post:"
echo "   • Click edit on own post"
echo "   • Modify content"
echo "   • Save changes"
echo "   • Verify update"
echo ""

echo "7. Delete Post:"
echo "   • Click delete on own post"
echo "   • Confirm deletion"
echo "   • Verify post removed"
echo ""

echo "8. Profile Page:"
echo "   • Click on username"
echo "   • View profile"
echo "   • Check recent activity"
echo ""

echo "9. Search:"
echo "   • Use search functionality"
echo "   • Test different queries"
echo "   • Verify results"
echo ""

echo "10. Logout:"
echo "   • Click logout"
echo "   • Verify redirect to home"
echo "   • Confirm session ended"
echo ""

echo "=== Mobile Testing (Optional) ==="
echo ""
echo "If you have access to real devices:"
echo ""
echo "iOS Devices:"
echo "  1. Connect iPhone/iPad to same network"
echo "  2. Find your local IP: ifconfig | grep 'inet '"
echo "  3. Open Safari on device: http://YOUR_IP:3000"
echo ""
echo "Android Devices:"
echo "  1. Connect Android device to same network"
echo "  2. Find your local IP: ifconfig | grep 'inet '"
echo "  3. Open Chrome on device: http://YOUR_IP:3000"
echo ""

echo "=== Checklist ==="
echo ""
echo "For EACH browser, verify:"
echo "  [ ] Pages load without errors"
echo "  [ ] CSS renders correctly"
echo "  [ ] JavaScript works (no console errors)"
echo "  [ ] Forms submit successfully"
echo "  [ ] Buttons and links work"
echo "  [ ] Images load properly"
echo "  [ ] Markdown renders correctly"
echo "  [ ] Modal dialogs work"
echo "  [ ] Navigation is smooth"
echo "  [ ] No horizontal scrolling at any breakpoint"
echo "  [ ] Text is readable (not too small)"
echo "  [ ] Touch targets are large enough (mobile)"
echo ""

echo "=== Recording Results ==="
echo ""
echo "Document your findings in:"
echo "  docs/k8s-tasks/TASK-6.8-CROSS-BROWSER-TESTING-REPORT.md"
echo ""
echo "For each browser, note:"
echo "  • Browser name and version"
echo "  • Operating system"
echo "  • Any issues found"
echo "  • Screenshots if needed"
echo ""

echo "=== Quick Browser Launch Commands (macOS) ==="
echo ""
echo "Chrome:   open -a 'Google Chrome' http://localhost:3000"
echo "Firefox:  open -a Firefox http://localhost:3000"
echo "Safari:   open -a Safari http://localhost:3000"
echo "Edge:     open -a 'Microsoft Edge' http://localhost:3000"
echo ""

echo "=== Quick Browser Launch Commands (Linux) ==="
echo ""
echo "Chrome:   google-chrome http://localhost:3000 &"
echo "Firefox:  firefox http://localhost:3000 &"
echo "Chromium: chromium-browser http://localhost:3000 &"
echo ""

echo "=== Tips ==="
echo ""
echo "• Use browser DevTools Console to check for JavaScript errors"
echo "• Use Network tab to monitor API calls and load times"
echo "• Use Lighthouse to check performance and accessibility"
echo "• Test in private/incognito mode to avoid cache issues"
echo "• Clear browser cache between tests if needed"
echo ""

read -p "Press Enter to open Chrome DevTools documentation..."
echo "Chrome DevTools: https://developer.chrome.com/docs/devtools/"
echo "Firefox DevTools: https://firefox-source-docs.mozilla.org/devtools-user/"
echo "Safari DevTools: https://developer.apple.com/safari/tools/"
echo ""

echo -e "${GREEN}Happy Testing!${NC}"
echo ""
